### ISSUE TITLE
Obsolete SDK versions

### ISSUE THREAD

**Issue by berkus** [TwilioDevEd/twiliochat-android#14]
JFYI, `compile "com.twilio:chat-android:0.11.2"` is a pre-release version that is no longer supported and it will not even connect nowadays.

**Comment by berkus** [comment]
There's also [a bundled 0.7.0 version](https://github.com/TwilioDevEd/twiliochat-android/blob/master/app/libs/twilio-ip-messaging-android.jar) in `app/libs` for some reason, that shouldn't work either.

**Comment by jefflinwood** [comment]
Hi - I'm in the process of updating this example application for the latest Chat SDK - the first step was just getting it up to speed for the latest Android build tools with https://github.com/TwilioDevEd/twiliochat-android/pull/13 - the next steps will be updating the SDK version and modifying all of the Java code.

**Comment by berkus** [comment]
Cool! Ping me if you need help.

**Comment by jefflinwood** [comment]
Updated in https://github.com/TwilioDevEd/twiliochat-android/pull/16
