### ISSUE TITLE
E/Volley: [48825] BasicNetwork.performRequest: Unexpected response code 404 for http://2cd82d50.ngrok.io/token

### ISSUE THREAD

**Issue by ravichoudhary33** [TwilioDevEd/twiliochat-android#8]
Please help...

**Comment by mcelicalderon** [comment]
Hey @ravichoudhary33 ! It looks like you might not be running a local development server and exposing it through Ngrok. Please refer to these steps https://github.com/TwilioDevEd/twiliochat-android#local-development and lets us know if you are still having problems with the app 😄

**Comment by ProfKengne** [comment]
[2927] BasicNetwork.performRequest: Unexpected response code 404
