### ISSUE TITLE
Provided Grant token is not authenticated or expired

### ISSUE THREAD

**Issue by iamjitendrasinh** [TwilioDevEd/twiliochat-android#9]
When i try to run code using twilio function it always throw error. please help.
![device-2018-01-25-104329](https://user-images.githubusercontent.com/34541797/35371881-d477e0b2-01bc-11e8-95df-9405263040a5.png)

**Comment by mcelicalderon** [comment]
Are you getting a fresh token using any of the server apps? A token is valid only for a limited time, you can configure how long in the server app.
